# main text of home
name: Hienifer Morales
bio: Creo que el futuro pertenece a quienes son capaces de adaptarse al cambio

# twitter summary info
description: A blog about technology and stuff related

picture: assets/images/picture.jpg

url: http://koppl.in/violet
# your url: http://USERNAME.github.io

# if you don't have any of social below, comment the line
facebook: Jenni Morales 
twitter: mo_rales07
github: Hienifer-Morales
email: hienifer@gmail.com
gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor] 
